import type { BlogPost } from './content';

const published = '2026-10-06';

export const moreGuidePosts: BlogPost[] = [
  {
    slug: 'when-a-gutter-is-the-leak-not-the-roof',
    serviceSlug: 'roof-repairs',
    category: 'Roof repairs',
    title: 'When a gutter is the leak, not the roof',
    seoTitle: 'Gutter Leak Dublin | Hopper and Outlet Faults',
    keywords: ['gutter repair dublin', 'leaking gutter dublin', 'blocked hopper', 'roof leak from gutter', 'kellys roofing'],
    excerpt: 'How an overflowing gutter, hopper or downpipe in Dublin puts water indoors while the slates are still sound.',
    readTime: '8 min read',
    imageKey: 'repair',
    heroImage: '/blog/blog-gutter-01.jpg',
    heroAlt: 'Rain overflowing a gutter on a Dublin brick house',
    publishedLabel: 'Gutters',
    publishedDate: published,
    modifiedDate: published,
    metaDescription: 'When a Dublin leak is the gutter, hopper or downpipe rather than the slates: signs, safe checks from the ground, and what a repair includes.',
    dek: 'Water high on a wall is often a gutter fault. Kellys Roofing & Interiors, a Dublin contractor since 2009, traces the eaves before anyone lifts a sound slate.',
    relatedSlugs: ['first-hour-of-a-roof-leak-in-dublin', 'storm-damage-roof-check-from-the-ground', 'flat-roof-leak-over-a-kitchen-extension'],
    faqs: [
      { question: 'Can a blocked gutter look like a roof leak?', answer: 'Yes. Overflow at the eaves can wet the top of a wall and show up indoors while the slates or tiles are still doing their job.' },
      { question: 'Should I clear a hopper from a ladder in the rain?', answer: 'No. Wet ladders and overflowing hoppers are a fall risk. Photograph the overflow from the ground and arrange safe access.' },
      { question: 'Do you repair gutters in Dublin?', answer: 'Yes. Kellys Roofing & Interiors, based in Dublin 8, repairs gutters, hoppers, outlets and the roof junctions they serve across Dublin.' },
    ],
    sections: [
      {
        heading: 'How can a gutter leak look like a roof leak?',
        image: '/blog/blog-gutter-01.jpg',
        imageAlt: 'A gutter overflowing in Dublin rain',
        paragraphs: [
          'A gutter leak in Dublin often looks like a roof leak because the water enters at the eaves and shows up high on a wall or in the corner of a ceiling. The covering can still be sound. What has failed is the outlet, the joint, the hopper, or a downpipe that no longer reaches the gully. Kellys Roofing & Interiors is based in Dublin 8 and has traced this path on houses across the city since 2009. We would rather clear a blocked outlet than sell a new roof for a stain the slates did not cause.',
          'Cast-iron eaves on older brick houses, and plastic gutters on later estates, both overflow when leaves, moss and grit close the outlet. The water then runs back toward the fascia or down the face of the wall. Indoors, the mark is usually at the edge of the room, not in the middle of the ceiling under an open slope. That position is the clue. Tell us if the stain sits in a corner under the gutter line.',
        ],
      },
      {
        heading: 'What does a blocked hopper do?',
        image: '/blog/blog-gutter-02.jpg',
        imageAlt: 'A hopper head packed with wet leaves',
        paragraphs: [
          'A hopper is the box that collects several gutters or a valley and passes the water into a downpipe. When it is packed with leaves it fills, and the water comes out of the top or the back. On a Dublin terrace that hopper is often tucked behind a fascia or at the end of a valley you can only see from a certain window. The overflow wets the wall head. From there it can track inside and look exactly like a failed flashing.',
          'Do not climb a wet ladder to scoop a hopper by hand in the rain. Photograph the overflow, the stained wall, and the downpipe from the ground. Note whether it happens in ordinary rain or only in a downpour. A hopper that copes with drizzle and fails in heavy rain may be undersized or only partly blocked. We confirm that from safe access, then clear it or replace the outlet, and we say if the gutter fall is wrong so the same blockage will return.',
        ],
      },
      {
        heading: 'Which outside marks should I look for?',
        image: '/blog/blog-gutter-03.jpg',
        imageAlt: 'A dark water streak on a wall under a gutter',
        paragraphs: [
          'Look for a dark vertical streak under a joint, a green line on the brick, a drip from a union, or a gutter that sags so water sits instead of running to the outlet. Look at the shoe at the bottom of the downpipe. If it has come away, water misses the gully and soaks the base of the wall, which is a different damp problem from a ceiling stain but part of the same system. Kellys Roofing treats the gutter, the hopper and the downpipe as one route.',
          'From indoors, a gutter leak prefers the perimeter. Paint bubbles at the top of an external wall. A corner ceiling stains after rain while the centre of the room stays dry. The attic, if you can look safely from a boarded path, may show wetness at the eaves rather than under a middle rafter. If you cannot look safely, do not. The outside streak is enough to aim the first visit at the eaves.',
        ],
        bullets: [
          'Overflow at a joint, outlet or hopper.',
          'A stain at the corner of a ceiling, not the centre.',
          'A sagging gutter that holds water.',
          'A downpipe shoe missing the gully.',
        ],
      },
      {
        heading: 'When is the roof still the cause?',
        image: '/blog/blog-gutter-04.jpg',
        imageAlt: 'A downpipe shoe that misses the gully',
        paragraphs: [
          'Gutters are not always the answer. A valley that overflows, a slipped slate just above the eaves, or a failed soaker can wet the same corner. We do not stop at the hopper if the covering above it is letting water under the slates. The inspection follows the water from the highest point that can reach that stain down to the gully. If both a gutter joint and a slate are wrong, the quote says so as two items.',
          'Flat roofs that discharge into a small outlet have the same logic. A kitchen extension can leak because the outlet is blocked, not because the membrane has split. That is a different page of advice, but the first question is the same: where is the water supposed to leave, and is that opening actually open? Kellys Roofing would rather show you a cleared outlet than a theory.',
        ],
      },
      {
        heading: 'What does a gutter repair include?',
        image: '/blog/blog-gutter-05.jpg',
        imageAlt: 'Damp at the top corner of an internal wall',
        paragraphs: [
          'A straightforward repair clears the blockage, remakes a failed joint, resets the fall, or refits a downpipe so it discharges into the gully. Perished plastic and cracked cast iron are replaced where they no longer hold water. Brackets that have pulled out of the fascia are put back into sound timber, not into rot. If the fascia itself is decayed, we say that before we hang a new gutter on it. The indoor stain is left to dry once the overflow has stopped.',
          'We do not recommend a full reroof because a gutter overflow stained a bedroom corner. We also do not pretend a lick of sealant on a split union will last a Dublin winter. The repair should match the material that is already there and should leave the outlet visible enough that you can see, from the ground, that water is leaving the gutter in the next heavy shower.',
        ],
      },
      {
        heading: 'How do I report a gutter leak in Dublin?',
        image: '/blog/blog-gutter-06.jpg',
        imageAlt: 'A cleared gutter outlet on a slate roof',
        paragraphs: [
          'Send the address, a photo of the indoor corner, and a photo of the overflowing gutter or stained wall. Say whether it happens in all rain or only in downpours, and whether leaves have been a problem. Kellys Roofing & Interiors will quote gutter and roof repairs for that house. We are based in Dublin 8 and we work across the city, including estates with long gutter runs and terraces with shared downpipes.',
          'Stay off the ladder. If water is entering now, catch it and keep it off electrics, using the same first-hour care as any other leak. Mention if the mark is new after wind, because a gutter pulled off a bracket is a storm fault as well as a drainage fault. The photos from the pavement are the right start. We will tell you whether the visit is a gutter repair, a roof junction, or both.',
          'After the outlet runs, watch the corner through the next rainfall. A mark that stops growing is drying. A mark that returns means water is still getting past the eaves or under the covering just above them. Tell us what you see. A gutter repair is finished when the water leaves the roof at the outlet you can point to, not when the ceiling has been painted. Kellys Roofing would rather be called back to a joint that still weeps than leave that joint behind new emulsion.',
          'When you write to us, name the side of the house and whether the overflow is at a hopper, a running outlet or a joint in the gutter itself. A hopper on a rear return is a different visit from a length of gutter that has left the fascia on the street elevation. If a downpipe discharges onto a flat roof or into a gulley that is already full, say that too. Water that leaves the gutter and then has nowhere to go will find the wall. Kellys Roofing & Interiors, based in Dublin 8, treats that path as part of the repair, not as a separate mystery after the brackets are tight. Clear what you can reach safely from the ground, leave the ladder work to us, and keep the photos of the overflow. Those pictures decide whether we bring a short length of gutter, a new outlet, or both.',
          'If the fascia behind the gutter is soft, or the brackets have pulled out of rotten timber, say that in the same note. A new length of gutter on a failed board will sag again. Kellys Roofing treats the timber and the outlet as one visit when that is what the photos show, and we will not ask you to paint the soffit as if that were the repair.',
        ],
      },
    ],
  },
  {
    slug: 'slate-or-tile-repair-or-replace-dublin',
    serviceSlug: 'roof-replacement',
    category: 'Roof replacement',
    title: 'Slate or tile: repair or replace on a Dublin house',
    seoTitle: 'Slate or Tile Roof Dublin | Repair or Replace',
    keywords: ['slate roof repair dublin', 'tile roof replacement dublin', 'repair or reroof', 'concrete tiles dublin', 'kellys roofing'],
    excerpt: 'How to tell whether a Dublin slate or tile roof needs local repairs or a planned replacement.',
    readTime: '8 min read',
    imageKey: 'replacement',
    heroImage: '/blog/blog-slate-01.jpg',
    heroAlt: 'Natural slate on a Victorian Dublin roof',
    publishedLabel: 'Repair or replace',
    publishedDate: published,
    modifiedDate: published,
    metaDescription: 'Slate or concrete tile on a Dublin house: when a local repair is enough, and when replacement is the more honest scope.',
    dek: 'Age alone does not decide. Kellys Roofing & Interiors, roofing in Dublin since 2009, looks at how widely the covering has failed before talking about a new roof.',
    relatedSlugs: ['chimney-flashing-leaks-dublin-terraces', 'planning-a-roof-replacement-for-a-dublin-home', 'storm-damage-roof-check-from-the-ground'],
    faqs: [
      { question: 'Does an old slate roof always need replacing?', answer: 'No. A Dublin slate roof with one slipped or cracked area can often be repaired if the rest of the covering and the fixings are still sound.' },
      { question: 'When is replacement the better choice?', answer: 'When defects are widespread, nails have failed across a slope, or concrete tiles are delaminating, a local patch is poor value.' },
      { question: 'Will you give a price for a new roof on this page?', answer: 'No. A new roof price depends on the house, access and specification. Kellys Roofing quotes that after a look, not from a guess.' },
    ],
    sections: [
      {
        heading: 'What is the difference between slate and tile in Dublin?',
        image: '/blog/blog-slate-01.jpg',
        imageAlt: 'Close view of natural slate courses',
        paragraphs: [
          'Natural slate is the covering on many Victorian and Edwardian Dublin terraces. It is thin, laid to a gauge, and usually fixed with nails. Concrete tiles are the covering on a lot of later suburban houses. They are heavier, interlocking, and they weather by the surface flaking rather than by a single slate slipping. Kellys Roofing & Interiors, based in Dublin 8, repairs both. The decision is not which material sounds better in a brochure. It is which material is on your house and how much of it has failed.',
          'A street can hold both. One house keeps its slate. The next was retiled. Mixing them on one roof without thinking about weight, gauge and detail is how leaks start at the junction. If we recommend a repair, it matches the covering you have. If we recommend replacement, we say what the new covering will be and what has to change in the battens, the underlay and the edges.',
        ],
      },
      {
        heading: 'When is a repair enough?',
        image: '/blog/blog-slate-03.jpg',
        imageAlt: 'Slipped slates leaving a gap in an old roof',
        paragraphs: [
          'A repair is enough when the failure is local. A few slipped slates, a cracked tile, a ridge that has opened, or a verge that needs remaking can be put right without stripping the slope. The rest of the covering should still be flat, fixed, and not shedding its surface. Nail sickness, where the nails have rusted and many slates are held by friction, is not a few slipped slates. We will tell you if a “small repair” would only be the first of a row of call-backs.',
          'Storms displace sound slates. That is a repair if the nails and the underlay are otherwise fine. Delamination of concrete tiles across a whole slope is not a repair. We do not sell replacement because a roof is old, and we do not sell a patch because replacement sounds expensive. The scope follows the extent of the defect. You should be able to see that extent in the notes and the photos from the visit.',
        ],
      },
      {
        heading: 'When is replacement the honest scope?',
        image: '/blog/blog-slate-04.jpg',
        imageAlt: 'Concrete roof tiles with the surface flaking away',
        paragraphs: [
          'Replacement is the honest scope when the covering has failed in many places, when the underlay is gone, or when the fixings can no longer be trusted. Widespread slipping, tiles that crumble in the hand, and a roof that has already been patched in several unrelated spots are the usual signs. Access, scaffolding and the chance to renew battens and eaves details then belong in one planned job rather than in a sequence of emergencies.',
          'We still do not publish a stock price for a new roof. The cost depends on the area of the roof, the covering, the chimneys, the access on a Dublin street, and whether the deck or the rafters need work we cannot see until the covering is off. A quote after a survey is the number that means something. A number guessed from the footpath does not. Our replacement guide explains how that specification is built up.',
        ],
        bullets: [
          'Many slipped or crumbling units, not one or two.',
          'Fixings that have failed across a slope.',
          'Underlay that no longer protects the roof.',
          'Repeated patches in unrelated places.',
        ],
      },
      {
        heading: 'How should the material be chosen?',
        image: '/blog/blog-slate-02.jpg',
        imageAlt: 'Concrete tiles on a suburban Dublin house',
        paragraphs: [
          'If the roof is to be recovered, the new material has to suit the structure and the street. Natural slate is lighter than many concrete tiles. A roof built for slate is not automatically ready for a heavier tile. A tile roof that is being retiled needs a specification for the interlocking detail, the eaves and the ridge, not a vague promise of “new tiles”. Leadwork at chimneys and valleys should be in the same scope, or the new covering will leak at the old junctions.',
          'Kellys Roofing writes that specification in words you can compare. We say what is included and what is not. We say if a chimney flashing is part of the job. We say if insulation and ventilation need a decision before the covering goes back, because closing a roof without a ventilation path is how condensation gets mistaken for another leak. You do not need a lecture. You need a scope you can accept or question.',
        ],
      },
      {
        heading: 'What can I see from the ground?',
        image: '/blog/blog-slate-06.jpg',
        imageAlt: 'Neighbouring Dublin roofs, one slate and one tile',
        paragraphs: [
          'From the pavement you can see slipped slates, a dip in a slope, a ridge that has stepped out of line, and tiles that look pitted. You cannot see nail condition or underlay. Do not climb up to find out. Photograph the slope, the chimney and any daylight gap you can see from a window. Note whether rooms have stained after wind. That is the pack we need to decide whether the first visit is a repair or a survey for replacement.',
          'A house in an estate of concrete tiles and a house in a slate terrace are not the same job. Say which you have, or send a photo of the street if you are unsure. We work on both across Dublin from our base in Dublin 8. The recommendation will name the covering we found, not a generic “roof”.',
        ],
      },
      {
        heading: 'How do I ask which scope I need?',
        image: '/blog/blog-slate-05.jpg',
        imageAlt: 'A single slate being replaced among older slates',
        paragraphs: [
          'Send the address, photos of the roof from the ground, and photos of any indoor stains. Say if you want a repair of a known slipped slate or advice on whether the whole slope is finished. Kellys Roofing & Interiors will tell you which of those we can see, and we will quote the one that matches the evidence. If we need a closer inspection before choosing, we say that too, rather than guessing a reroof to be safe.',
          'Repair and replacement are both proper outcomes. The wrong outcome is a patch on a roof that cannot hold it, or a new roof on a slope that needed six slates and a ridge. Ask us for the distinction in writing. That is the document to keep with the house, whether you live in a slate terrace or a tiled estate.',
          'If a storm has just moved slates that were otherwise tight, treat it as a repair first and read the ground check for wind damage before you assume the roof is at the end of its life. If the same slope has shed slates in calm weather for several years, say that. History of movement matters as much as the photograph from this morning. Kellys Roofing uses both. A single wet day does not condemn a roof, and a quiet week does not prove a failing fixing.',
          'Ask us to write the choice in plain language: repair this slope, or replace this slope, and why. A mixed roof, slate on the front and tile on the rear, can need two answers. An extension roof is a third answer and belongs with the flat-roof note, not with the main covering. Kellys Roofing will not fold those into one price guess on a page. The visit is what makes the split honest. If nails are failing across a whole slope, say whether slates are landing in the garden in calm weather. If only the verge or the ridge has moved after wind, say that instead. The first is a fixing problem. The second is often a local storm repair. Bring photos of the covering from the street and of any pieces you have picked up. We would rather see the material in your hand than hear a colour name. Concrete tile, natural slate and fibre cement do not take the same repair, and a wrong match is how the next leak starts beside the one we have just closed.',
          'If you are unsure of the material, do not guess a product name from a neighbour’s roof. A photo of the edge, where the thickness shows, is more useful than a colour. Kellys Roofing will name the covering on the visit and say whether a repair can match it. Until then, leave slipped pieces on the ground where they fell, out of the path, so we can see them.',
        ],
      },
    ],
  },
  {
    slug: 'flat-roof-leak-over-a-kitchen-extension',
    serviceSlug: 'flat-roofing',
    category: 'Flat roofing',
    title: 'Flat roof leaking over a kitchen extension',
    seoTitle: 'Flat Roof Leak Dublin | Kitchen Extensions',
    keywords: ['flat roof leak dublin', 'extension flat roof', 'kitchen extension roof leak', 'ponding flat roof', 'kellys roofing'],
    excerpt: 'Why a Dublin kitchen extension leaks at the outlet, the upstand or the junction with the house, and what to do first.',
    readTime: '8 min read',
    imageKey: 'flat',
    heroImage: '/blog/blog-extension-01.jpg',
    heroAlt: 'A flat-roofed kitchen extension on a Dublin terrace',
    publishedLabel: 'Extensions',
    publishedDate: published,
    modifiedDate: published,
    metaDescription: 'A leaking flat roof over a Dublin kitchen extension: ponding, blocked outlets, upstands, and how Kellys Roofing tells a repair from a renewal.',
    dek: 'Most extension leaks are at the outlet or the wall junction, not in the middle of a sound membrane. Kellys Roofing & Interiors has traced these roofs across Dublin since 2009.',
    relatedSlugs: ['when-a-gutter-is-the-leak-not-the-roof', 'flat-roof-guide-for-dublin-extensions', 'repairing-interiors-after-a-roof-leak'],
    faqs: [
      { question: 'Is a stain in a kitchen extension always a split membrane?', answer: 'No. A blocked outlet or a failed upstand where the flat roof meets the house wall is a common cause on Dublin extensions.' },
      { question: 'Can I go on the flat roof to check the puddle?', answer: 'No. A wet flat roof is slippery and may not be safe to walk. Photograph ponding from a window and arrange proper access.' },
      { question: 'Do you repair extension flat roofs in Dublin?', answer: 'Yes. Kellys Roofing & Interiors, based in Dublin 8, repairs and renews flat roofs on extensions, garages and similar roofs across Dublin.' },
    ],
    sections: [
      {
        heading: 'Where does an extension roof usually leak?',
        image: '/blog/blog-extension-01.jpg',
        imageAlt: 'Rear extension with a flat roof on a Dublin house',
        paragraphs: [
          'A kitchen extension in Dublin usually leaks at the place water is supposed to leave, or at the place the flat roof meets the main house. That is the outlet, the gutter it falls into, or the upstand and flashing against the brick wall. The stain indoors often sits near the original back wall or under a roof light, which is a clue to the junction rather than a random split in the middle of the sheet. Kellys Roofing & Interiors is based in Dublin 8 and has followed this pattern on terraces and estates since 2009.',
          'Ponding makes the problem look worse than the hole. A shallow pool after rain can mean the falls are poor, the outlet is blocked, or both. Water that sits will find the weakest lap. Clearing a blocked outlet is sometimes the whole repair. A tired membrane with water sitting across it is a different job. We say which one we are looking at before we recommend a full renewal.',
        ],
      },
      {
        heading: 'What does ponding tell you?',
        image: '/blog/blog-extension-02.jpg',
        imageAlt: 'Rainwater ponding on a flat roof',
        paragraphs: [
          'A little water just after a shower can be normal while it drains. A pool that is still there the next day is not. It means the outlet is higher than the low point, the deck has slumped, or debris has closed the opening. Leaves and grit around a small circular outlet are enough to hold a pond on a kitchen roof. From an upstairs window you can often see that silver patch of water without stepping onto the roof.',
          'Do not walk a wet flat roof to prod the puddle. The surface is slippery, and some decks were never meant to be walked. Photograph the pond, the outlet if you can see it, and the ceiling stain. Note whether the leak appears only when the pond is deep. That timing tells us the water is getting in under pressure at a lap or an upstand, not through a drip in dry weather.',
        ],
      },
      {
        heading: 'Why do outlets and upstands fail?',
        image: '/blog/blog-extension-03.jpg',
        imageAlt: 'A blocked outlet on a small flat roof',
        paragraphs: [
          'Outlets on extensions are small. They clog. The collar around them cracks. A leaf guard is missing, or it is so fine that it blocks itself. When the outlet cannot take a Dublin downpour, water rises and crosses a seam that was fine at a lower level. The upstand against the house is the other weak line. Lead or a membrane turn-up that has pulled out of the chase lets water run down the original wall and into the kitchen along the head of that wall.',
          'A repair that only paints a coating over the middle of the roof and leaves a blocked outlet will fail again in the next heavy rain. Kellys Roofing includes the outlet and the wall junction in the look, not as an extra afterthought. If the deck under the membrane has gone soft, coating it is the wrong scope. We will say if the board needs to come off.',
        ],
        bullets: [
          'Water still sitting the day after rain.',
          'Leaves packed around the outlet.',
          'Staining where the extension meets the house.',
          'A drip under a roof light or an internal corner.',
        ],
      },
      {
        heading: 'How do we tell a repair from a renewal?',
        image: '/blog/blog-extension-04.jpg',
        imageAlt: 'Flashing where a flat roof meets a brick wall',
        paragraphs: [
          'A local repair is right when the membrane is largely sound and the leak is an outlet, a split at one lap, or a flashing that has left the wall. Renewal is right when the sheet is brittle, blistered across the roof, or the deck has lost its fall so every repair would sit in a pond. We do not sell a new roof because one collar has failed, and we do not sell a patch on a deck that holds water by design.',
          'The quote should name the system we found, what we propose, and whether insulation or a warm-roof build-up is part of the conversation. Many Dublin extensions were built with little insulation. Changing that is a decision, not something to hide inside a like-for-like repair. Our flat-roof guide sets out falls, edges and condensation in more detail. This page is about the leak you can see in the kitchen.',
        ],
      },
      {
        heading: 'What should I do while it is leaking?',
        image: '/blog/blog-extension-05.jpg',
        imageAlt: 'A water stain on a kitchen ceiling',
        paragraphs: [
          'Catch the drip, move food and electrics out of the way, and do not climb onto the extension. If a roof light is streaming, keep clear of the opening. Photograph the ceiling and, from a safe window, the pond or the outlet. Those are the first-hour steps, the same as any other Dublin leak. Painting the ceiling before the outlet is open will trap the stain and the moisture.',
          'If the extension gutter is overflowing onto the flat roof, say that too. Sometimes the leak is the gutter that was meant to take the main roof, dumping onto a roof that cannot shed it. Kellys Roofing checks that relationship. A kitchen ceiling does not tell you which of those paths is active. The photos do.',
        ],
      },
      {
        heading: 'How do I ask for an extension roof quote?',
        image: '/blog/blog-extension-06.jpg',
        imageAlt: 'A renewed flat roof membrane with a clear outlet',
        paragraphs: [
          'Send the address, a photo of the kitchen stain, and a photo of the flat roof from an upstairs window if you can take one safely. Say how old the extension is if you know, and whether the leak follows heavy rain or a pond that sits. Kellys Roofing & Interiors will quote the inspection and the likely repair or renewal. We are based in Dublin 8 and we cover extension roofs across the city.',
          'Ask us to separate a blocked outlet from a failed membrane in the note we leave you. That sentence is what stops the next contractor from starting again from zero. When the roof is weather-tight, the ceiling can dry. Until then, keep the bowl in place and leave the decoration alone.',
          'If the same extension has leaked every autumn, say how many times and what was coated or patched. A history of surface coatings over a ponding deck is a reason to look at the falls, not to add another layer. Kellys Roofing would rather replace a small rotten area of deck and reset an outlet than spread another product across water that has nowhere to go. Tell us what you can see from the window the morning after rain. That photograph is often the whole diagnosis.',
          'Measure nothing from the kitchen floor and do not guess the roof area from the room. The deck can extend past the ceiling line, and a roof light or a lantern changes the falls. If you know who built the extension and roughly when, that is useful. Many Dublin kitchen roofs from the last twenty years used a single-ply sheet or a felt build-up with a small circular outlet, and the leak is at that outlet or at the upstand against the original wall. Older felt that has been coated more than once is a different conversation, because another coating will not restore a fall that was never there. Kellys Roofing & Interiors will say which of those we are looking at before any product is named. Keep furniture and electrics out of the drip until that visit. A bowl under the stain is still the right first step, the same as any other leak in the house, and painting the ceiling while the pond is still on the roof only stores the problem for the next wet week.',
          'If the leak is under a roof light, photograph the frame from inside and the upstand from the window above if you can do that without stepping onto the roof. A failed seal at the light is a different repair from a blocked outlet, and both can be wet on the same day. Tell us which one you can see. Kellys Roofing would rather open the right junction than coat the whole deck because the kitchen ceiling is stained in two places.',
        ],
      },
    ],
  },
  {
    slug: 'how-long-before-plastering-a-ceiling-after-a-leak',
    serviceSlug: 'interiors-building',
    category: 'Interiors & building',
    title: 'How long to leave a ceiling before plastering or painting',
    seoTitle: 'Ceiling Drying Time After a Roof Leak | Dublin',
    keywords: ['ceiling repair after leak', 'how long ceiling dry', 'plaster after roof leak', 'water stain ceiling dublin', 'kellys roofing'],
    excerpt: 'Why a Dublin ceiling should not be plastered or painted until the roof is sound and the material has dried.',
    readTime: '8 min read',
    imageKey: 'interiors',
    heroImage: '/blog/blog-ceiling-01.jpg',
    heroAlt: 'A dried tide mark on a ceiling after a leak has stopped',
    publishedLabel: 'After the leak',
    publishedDate: published,
    modifiedDate: published,
    metaDescription: 'How long to leave a Dublin ceiling after a roof leak before plastering or painting, and why the roof must be sound first.',
    dek: 'There is no honest one-day answer. Kellys Roofing & Interiors stops the leak first, then lets plaster and timber dry before any new finish goes on.',
    relatedSlugs: ['repairing-interiors-after-a-roof-leak', 'first-hour-of-a-roof-leak-in-dublin', 'flat-roof-leak-over-a-kitchen-extension'],
    faqs: [
      { question: 'Can I paint a ceiling the day the leak stops?', answer: 'No. Paint over a damp stain traps moisture and the mark usually returns. The roof must be sound and the ceiling dry first.' },
      { question: 'How long does a ceiling take to dry?', answer: 'It depends on how wet the plaster and timber are, and on ventilation. A light stain may take days. Saturated plaster can take much longer. A moisture check beats a guess.' },
      { question: 'Do you plaster after roof leaks in Dublin?', answer: 'Yes. Kellys Roofing & Interiors, based in Dublin 8, repairs the roof and then ceilings, plaster and related interior work once the area is ready.' },
    ],
    sections: [
      {
        heading: 'Why is there no fixed number of days?',
        image: '/blog/blog-ceiling-01.jpg',
        imageAlt: 'A yellow-brown tide mark on a ceiling',
        paragraphs: [
          'A ceiling dries when the water has somewhere to go and no new water is arriving. A light stain in warm weather with the windows open is not the same as saturated lath in a closed room in November. Kellys Roofing & Interiors, based in Dublin 8, will not promise that every ceiling is ready to plaster in three days or in three weeks. We look at whether the roof is weather-tight and whether the material is still wet.',
          'Painting on a calendar date is how stains return. The brown mark is often dirt and tannin carried by the water, and it can show through emulsion even after the plaster feels dry to the hand. Dry to the touch is not the same as dry enough to close. If you are deciding whether to book a plasterer, ask for a moisture check rather than a slogan.',
        ],
      },
      {
        heading: 'What has to happen before any plaster?',
        image: '/blog/blog-ceiling-02.jpg',
        imageAlt: 'A moisture meter held against stained plaster',
        paragraphs: [
          'The leak has to be stopped. Plastering under an active roof leak wastes the work. That means the slate, tile, flashing, gutter or flat-roof outlet that was letting water in has been dealt with, and a spell of rain has not brought the stain back. Only then does drying time mean anything. Until that test, the ceiling is still a symptom.',
          'Electrics that were wet need to be safe before anyone boards or skims around them. A downlight full of water is not a decorating detail. Leave it alone until it has been checked. We coordinate ceiling repairs with the roof repair so the room is not closed while the entry is still open. That sequence is the whole point of treating the roof and the room as one job.',
        ],
      },
      {
        heading: 'What can dry, and what should come out?',
        image: '/blog/blog-ceiling-03.jpg',
        imageAlt: 'A small area of ceiling opened back to the laths',
        paragraphs: [
          'A surface stain on sound plaster can dry in place. Plaster that is soft, sagging, or moulding on the back should come out. Insulation that is soaked and slumped should not be left against the ceiling. Timber that is wet can stay if it is sound and can vent, and it should be replaced if it is decayed. Kellys Roofing would rather open a small soft area than skim over a wet lath that will fail next winter.',
          'The decision is visible. If the ceiling has dropped, keep people out from under it. If it is only marked, leave it uncovered so air can reach it. Do not screw a new board over a wet ceiling to make the room look finished for a viewing or a weekend. That board becomes a lid on the moisture.',
        ],
        bullets: [
          'Roof confirmed weather-tight before plaster.',
          'Soft or sagging plaster removed, not skimmed.',
          'Wet insulation taken out where it is holding water.',
          'Electrics checked before the ceiling is closed.',
        ],
      },
      {
        heading: 'How should the room be dried?',
        image: '/blog/blog-ceiling-04.jpg',
        imageAlt: 'A room drying with a window open and a dehumidifier',
        paragraphs: [
          'Ventilation does more than heat on its own. Open the room when the weather allows, keep furniture off the wet corner, and use a domestic dehumidifier if you have one and the room can be closed around it for part of the day. Do not aim a heater at a soaked ceiling and leave the windows shut. You will drive moisture into the next bay. Gentle, steady drying beats a weekend of blasting.',
          'We still do not give a universal day count. A ceiling that was wet for an hour is not a ceiling that was wet for a month. Ask us what we found in the roof and in the plaster. If we are doing the interior work as well, we will not skim until we are content the background is ready. If another contractor is plastering, give them that same test, not a date picked to suit a diary.',
        ],
      },
      {
        heading: 'When is plaster and paint appropriate?',
        image: '/blog/blog-ceiling-05.jpg',
        imageAlt: 'A fresh plaster patch on a ceiling',
        paragraphs: [
          'Plaster goes on when the background is stable and dry enough for the product being used. New plaster then needs its own drying time before paint. A stain-block is often required even on a dry ceiling, because the mark is in the material, not only on the surface. Painting the whole ceiling usually looks better than a spot of colour that never quite matches.',
          'Kellys Roofing & Interiors can carry the ceiling, plaster and making-good after the roof is secure, so you are not coordinating three people who each think the drying is someone else’s job. The scope should say what is being replaced and what is being left to dry. That is the note to keep with the photos of the leak.',
        ],
      },
      {
        heading: 'What should I watch after the ceiling is finished?',
        image: '/blog/blog-ceiling-06.jpg',
        imageAlt: 'An even painted ceiling after repair',
        paragraphs: [
          'Watch the same spot in the next heavy rain and again when the heating season starts. A mark that stays pale and does not grow is a historical stain or a finish that has done its job. A mark that darkens or a new drip means the roof path is open again, or a second path was missed. Tell us. Do not keep repainting a growing stain.',
          'Send the address and say the roof has already been repaired, when, and what the ceiling is doing now. If the roof has not been repaired yet, start there. Plaster on a wet leak is not a finish. It is a cover. Kellys Roofing, from Dublin 8, would rather be slow about the ceiling and sure about the roof.',
          'If you are a landlord or you are selling, write down the date the roof was made good and the date the ceiling was closed. Buyers and tenants ask that question, and a guess reads as if the leak is still a mystery. The honest answer is a sequence: source stopped, materials dried or replaced, then plaster and paint. That sequence is what we put in the quote when we are asked to do both the roof and the room.',
          'Drying is slower in a closed Dublin winter than in a room you can air. A ceiling that was wet for one storm may be ready for a stain-block and paint once a moisture check is content. A ceiling that has been damp for a season, with soft plaster or insulation sitting on the back, is not on that timetable. Opening the soft area, taking out what is holding water, and letting the timber vent is the work that makes a later skim last. Heat aimed at a closed wet ceiling drives moisture into the next bay. A dehumidifier helps when the room can be shut for part of the day and the roof above is already sound. Neither replaces the check. Kellys Roofing & Interiors will not put a date on the paint until that check has been done, and we will not let a viewing or a handover pick the date either.',
          'If another trade is plastering, give them the same test we use: the roof has stayed dry through rain, the background is stable, and anything that was saturated has been removed or has dried. New plaster then needs its own time before emulsion, and a stain-block is often required because the brown mark is in the material. Spot-painting a tide line rarely matches. The whole ceiling is usually the honest finish. Keep the photos of the original leak with the date the roof was made good. If a mark returns after that, it is a new event or a missed path, and it should come back to us before anyone paints it again. From our base in Dublin 8 we would rather be slow about the room and sure about the roof.',
          'A light surface mark can wait. Soft plaster, a sag, or a smell of damp in the insulation should not be closed up to suit a diary. Write down when the roof was made good and what the ceiling is doing now, and send both with the address. That is enough for us to say whether the room is ready.',
        ],
      },
    ],
  },
  {
    slug: 'storm-damage-roof-check-from-the-ground',
    serviceSlug: 'roof-repairs',
    category: 'Roof repairs',
    title: 'Storm damage: what to check from the ground',
    seoTitle: 'Storm Damage Roof Check Dublin | From the Ground',
    keywords: ['storm damage roof dublin', 'slates after wind', 'roof check after storm', 'emergency roof dublin', 'kellys roofing'],
    excerpt: 'What a Dublin householder can safely check from the ground after high wind, and what should wait for a roofer.',
    readTime: '8 min read',
    imageKey: 'repair',
    heroImage: '/blog/blog-storm-01.jpg',
    heroAlt: 'A wet Dublin street and slate roofs after wind and rain',
    publishedLabel: 'After a storm',
    publishedDate: published,
    modifiedDate: published,
    metaDescription: 'After high wind in Dublin, check the roof from the ground: debris, ridges, chimneys and gutters. Stay off the slates.',
    dek: 'The useful storm check is done from the pavement or the garden. Kellys Roofing & Interiors, roofing in Dublin since 2009, would rather see your photos than meet you on a wet roof.',
    relatedSlugs: ['first-hour-of-a-roof-leak-in-dublin', 'slate-or-tile-repair-or-replace-dublin', 'when-a-gutter-is-the-leak-not-the-roof'],
    faqs: [
      { question: 'Should I get on the roof after a storm?', answer: 'No. Check from the ground. Wet slates and wind are how people fall. Photograph what you can see and send it to a roofer.' },
      { question: 'What storm damage can I see without a ladder?', answer: 'Slates or tiles on the ground, a ridge out of line, a leaning chimney pot, and a gutter hanging off a bracket.' },
      { question: 'Do you attend storm-damaged roofs in Dublin?', answer: 'Yes. Kellys Roofing & Interiors, based in Dublin 8, repairs storm damage, slipped slates and pulled gutters across Dublin.' },
    ],
    sections: [
      {
        heading: 'What is a safe check after high wind?',
        image: '/blog/blog-storm-01.jpg',
        imageAlt: 'Dublin roofs after wind and rain',
        paragraphs: [
          'After high wind in Dublin, walk the pavement and the garden. Look up. Do not fetch a ladder. Kellys Roofing & Interiors is based in Dublin 8 and has been called to roofs the morning after Atlantic weather since 2009. The damage we can use is the damage you can see without leaving the ground: pieces of slate on the path, a ridge that has stepped, a pot that is no longer upright, a gutter that has left its bracket.',
          'If water is already coming inside, deal with people and electrics first, the same as any leak. The storm check does not outrank a bulging ceiling. Once the room is safe, the outside look from the ground tells us whether this is a few displaced slates or a wider failure. Photos in daylight are better than a tour of the roof in the dark.',
        ],
      },
      {
        heading: 'What does debris on the ground mean?',
        image: '/blog/blog-storm-02.jpg',
        imageAlt: 'Broken slate on a wet garden path',
        paragraphs: [
          'Slate or tile on the grass means something left the roof. It does not tell you how many more are loose. Pick the pieces up so they are not a hazard, and photograph them where they fell if you can do that safely. Look above that spot from a window. A gap you can see is a repair. A slope that looks entire from the street can still have lost fixings. Say what you found on the ground so we do not arrive expecting a gutter-only job.',
          'Moss, a ridge tile, or a length of flashing on the path is the same kind of evidence. Do not try to push a slate back into place with a pole. You will break the next one and you will not know whether the nail is holding. Leave the gap. A temporary cover from proper access is our job if rain is still getting in.',
        ],
      },
      {
        heading: 'Which lines on the roof should I look along?',
        image: '/blog/blog-storm-03.jpg',
        imageAlt: 'A ridge tile sitting out of line',
        paragraphs: [
          'Look along the ridge. A single tile cocked up is easy to see against the sky. Look at the verge, the edge of the roof, for a piece that has dropped. Look at hips if the house has them. These are the lines wind gets under. A ridge that was straight yesterday and is stepped today is storm damage, even if the ceiling is still dry. Dry today does not mean dry in the next shower, because the underlay may be all that is holding.',
          'Coastal houses and exposed hills, from Howth to the south coast, take this harder than a sheltered street. Say if your house faces open weather. An estate roof of concrete tiles can lose a ridge or a verge in the same wind that lifts slates on a terrace. The material differs. The ground check does not. You are looking for a line that is no longer straight and for pieces that are no longer on the roof.',
        ],
        bullets: [
          'Pieces of covering on the ground.',
          'A ridge, hip or verge out of line.',
          'Daylight through a gap you can see from a window.',
          'No ladder, no walking the slates.',
        ],
      },
      {
        heading: 'What about chimneys and gutters?',
        image: '/blog/blog-storm-04.jpg',
        imageAlt: 'A chimney pot slightly tilted after wind',
        paragraphs: [
          'A pot that leans, a cowl that has gone, or a chimney that has shed mortar is visible from the pavement if you stand far enough back. Do not lean out of a window to push it. Photograph it. A gutter that hangs on one bracket is also storm damage, and it will overflow into the wall as soon as it rains again. That can become an indoor leak even though the slates never moved.',
          'Kellys Roofing treats a pulled gutter and a shifted pot as items we can see and quote, not as reasons to strip the roof. If the stack itself looks cracked or newly out of plumb, say so and keep people away from that side of the house until it has been looked at. Most of what wind does to a Dublin roof is local. We will tell you if it is not.',
        ],
      },
      {
        heading: 'What if nothing looks wrong but the ceiling stained?',
        image: '/blog/blog-storm-05.jpg',
        imageAlt: 'A gutter pulled loose from one bracket',
        paragraphs: [
          'Wind-driven rain finds flashing and valleys that cope with vertical rain. The roof can look tidy from the street and still have let water under a lifted apron. If the ceiling stained and you cannot see debris, say that. The absence of slate on the grass does not mean the roof was untouched. It means the failure may be a joint, not a missing unit. Our chimney and gutter notes are the next place to look in the photos you send.',
          'Do not conclude that you need a new roof because a storm stained one room. Also do not conclude that a tidy ridge means there is nothing to do. Send the indoor photo and the best outside photo you can take from the ground. We will say whether it can wait or whether water is likely to return with the next blow.',
        ],
      },
      {
        heading: 'How do I send a storm report?',
        image: '/blog/blog-storm-06.jpg',
        imageAlt: 'Checking a roof from the garden, not from a ladder',
        paragraphs: [
          'Send the address, the time of the wind if you know it, photos from the ground, and a photo of any indoor stain. Say if anyone is under a bulging ceiling. Kellys Roofing & Interiors will use that to prioritise the visit. We are based in Dublin 8 and we cover storm repairs across the city. Stay off the roof until we have safe access.',
          'If the only finding is a gutter bracket, say that plainly. If slates are in the garden, say how many pieces you picked up. Those details change the materials we bring. A storm check from the ground is not a fuss. It is the difference between a repair and a fall. When the covering is secure again, any ceiling work waits until the roof has stayed dry.',
          'Keep the photos even if the stain fades the next day. Insurers and managing agents ask what moved, and a picture of a cocked ridge is better than a memory. Kellys Roofing can quote the making-good from those pictures and from the visit, and we will separate a storm repair from a roof that was already failing. Wind is not an excuse to replace a sound slope, and a sound-looking slope is not an excuse to ignore a pot that is no longer seated.',
          'Walk the boundary once in daylight and once is enough. Note debris, a ridge out of line, a verge that has dropped, a pot that leans, and a gutter on one bracket. Those five things are what we can use from the ground. Do not add a ladder so the list looks more complete. A wet slate and a gust are how people fall, and a photo from the garden is the record we want. If water is already inside, the indoor safety steps come first: people, electrics, and anything under a ceiling that has started to drop. The outside look waits until that room is safe. Kellys Roofing & Interiors will prioritise a house where the ceiling is moving over a house where a ridge tile is merely cocked and the rooms are dry. Say which one you are. Send the address, the photos, and whether the wind faced the front or the rear. Exposed coasts and open estates take the same check as a sheltered terrace. The material differs. The rule does not: stay on the ground, and let the roofer decide what the wind actually moved.',
          'If a neighbour’s slate is in your garden, leave it and say so. Shared valleys and party stacks mean the piece may not be yours, and putting it back on the wrong slope helps nobody. Kellys Roofing will sort the ownership on the visit. Your job the morning after the wind is the photographs, the people indoors, and staying off the roof.',
        ],
      },
    ],
  },
];
